name: Kubernetes CI with Kind

on:
  push:
    branches:
      - main

jobs:
  kind-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Kind cluster
      uses: helm/kind-action@v1.8.0
      with:
        wait: 60s  # Wait until cluster is ready

    - name: Show kubectl config
      run: kubectl config view

    - name: Check nodes (verify connection)
      run: kubectl get nodes

    - name: Apply Kubernetes manifests
      run: kubectl apply -f k8s/deployment.yaml
