name: Kubernetes CI using Kind

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Create Kubernetes cluster with Kind
      uses: helm/kind-action@v1.8.0
      with:
        wait: 60s  # Wait for cluster to be ready

    - name: Apply Kubernetes manifests
      run: kubectl apply -f k8s/deployment.yaml
